#!/bin/bash

# Stop previous instance of the bot if it's running
pkill Harold;

# Clean out previous build
rm -rf ~/bots/bin/Harold;

# Build bot
cd ~/bots/repos/Harold
git secret reveal -p '$1';
dotnet build -c Release -o ../../bin/Harold -p:PublishReadyToRun=true -p:PublishTrimmed=true --source=https://api.nuget.org/v3/index.json --source=https://nuget.emzi0767.com/api/v3/index.json;

# Set up and start the bot
cp config.json ../../bin/Harold/config.json;
cd ~/bots/bin/Harold;
./Harold;
