// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Norm.Database.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Norm.Migrations
{
    [DbContext(typeof(NormDbContext))]
    [Migration("20210712032238_Update_all_dependencies_and_tools")]
    partial class Update_all_dependencies_and_tools
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Norm.Database.Entities.GuildBackgroundJob", b =>
                {
                    b.Property<string>("HangfireJobId")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<int>("GuildJobType")
                        .HasColumnType("integer")
                        .HasColumnName("job_type");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_name");

                    b.Property<Instant>("ScheduledTime")
                        .HasColumnType("timestamp")
                        .HasColumnName("scheduled_time");

                    b.HasKey("HangfireJobId")
                        .HasName("hangfire_job_id");

                    b.HasIndex("GuildId", "ScheduledTime");

                    b.ToTable("all_guild_background_jobs");
                });

            modelBuilder.Entity("Norm.Database.Entities.GuildEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EventDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_desc");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("Id")
                        .HasName("guild_event_id");

                    b.HasIndex("GuildId");

                    b.ToTable("all_guild_events");
                });

            modelBuilder.Entity("Norm.Database.Entities.GuildLogChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("log_channel_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("Id")
                        .HasName("guild_log_channel_id");

                    b.HasIndex("GuildId");

                    b.ToTable("all_guild_log_channels");
                });

            modelBuilder.Entity("Norm.Database.Entities.GuildModerationAuditRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<int>("ModerationAction")
                        .HasColumnType("integer")
                        .HasColumnName("moderation_action");

                    b.Property<decimal>("ModeratorUserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("moderator_user_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Instant?>("Timestamp")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("audit_record_id");

                    b.HasIndex("GuildId");

                    b.ToTable("all_guild_moderation_audit_records");
                });

            modelBuilder.Entity("Norm.Database.Entities.GuildMovieNight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("AnnouncementChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("announcement_channel_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("HostId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("host_id");

                    b.Property<int>("MaximumRating")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_rating");

                    b.Property<string>("MovieNightStartHangfireId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("movie_night_start_hangfire_id");

                    b.Property<int>("NumberOfSuggestions")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_suggestions");

                    b.Property<string>("VotingEndHangfireId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voting_end_hangfire_id");

                    b.Property<decimal?>("VotingMessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("voting_message_id");

                    b.Property<string>("VotingStartHangfireId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voting_start_hangfire_id");

                    b.Property<string>("WinningMovieImdbId")
                        .HasColumnType("text")
                        .HasColumnName("winning_movie_imdb_id");

                    b.HasKey("Id")
                        .HasName("movie_night_id");

                    b.HasIndex("GuildId");

                    b.ToTable("all_guild_movie_nights");
                });

            modelBuilder.Entity("Norm.Database.Entities.GuildMovieSuggestion", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasColumnType("text")
                        .HasColumnName("imdb_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<Instant?>("InstantWatched")
                        .HasColumnType("timestamp")
                        .HasColumnName("instant_watched");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<decimal>("SuggesterId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("suggester_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("ImdbId", "GuildId");

                    b.ToTable("all_guild_movie_suggestions");
                });

            modelBuilder.Entity("Norm.Database.Entities.GuildNovelRegistration", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<int>("NovelInfoId")
                        .HasColumnType("integer")
                        .HasColumnName("novel_info_id");

                    b.Property<decimal>("AnnouncementChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("announcement_channel_id");

                    b.Property<bool>("IsDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_dm");

                    b.Property<decimal?>("MemberId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("member_id");

                    b.Property<bool>("PingEveryone")
                        .HasColumnType("boolean")
                        .HasColumnName("ping_everyone");

                    b.Property<bool>("PingNoOne")
                        .HasColumnType("boolean")
                        .HasColumnName("ping_no_one");

                    b.Property<decimal?>("RoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("role_id");

                    b.HasKey("GuildId", "NovelInfoId", "AnnouncementChannelId")
                        .HasName("guild_novel_registration_id");

                    b.HasIndex("NovelInfoId");

                    b.ToTable("guild_novel_registration");
                });

            modelBuilder.Entity("Norm.Database.Entities.GuildPrefix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.HasKey("Id")
                        .HasName("guild_prefix_id");

                    b.HasIndex("GuildId");

                    b.ToTable("all_guild_prefixes");
                });

            modelBuilder.Entity("Norm.Database.Entities.GuildWelcomeMessageSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("ShouldPing")
                        .HasColumnType("boolean")
                        .HasColumnName("should_ping");

                    b.Property<bool>("ShouldWelcomeMembers")
                        .HasColumnType("boolean")
                        .HasColumnName("should_welcome_members");

                    b.HasKey("GuildId")
                        .HasName("guild_id");

                    b.ToTable("all_guild_welcome_message_settings");
                });

            modelBuilder.Entity("Norm.Database.Entities.MovieNightAndSuggestion", b =>
                {
                    b.Property<int>("MovieNightId")
                        .HasColumnType("integer")
                        .HasColumnName("movie_night_id");

                    b.Property<string>("MovieSuggestionId")
                        .HasColumnType("text")
                        .HasColumnName("movie_suggestion_id");

                    b.Property<string>("EmojiId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emoji_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.HasKey("MovieNightId", "MovieSuggestionId");

                    b.HasIndex("MovieSuggestionId", "GuildId");

                    b.ToTable("movie_night_and_suggestion_join");
                });

            modelBuilder.Entity("Norm.Database.Entities.NovelInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("FictionId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("fiction_id");

                    b.Property<string>("FictionUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fiction_uri");

                    b.Property<decimal>("MostRecentChapterId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("most_recent_chapter_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("novel_name");

                    b.Property<string>("SyndicationUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("syndication_uri");

                    b.HasKey("Id")
                        .HasName("novel_info_id");

                    b.ToTable("novel_info");
                });

            modelBuilder.Entity("Norm.Database.Entities.UserTimeZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone_id");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_timezone_id");

                    b.HasIndex("UserId");

                    b.ToTable("all_user_time_zones");
                });

            modelBuilder.Entity("Norm.Database.Entities.GuildNovelRegistration", b =>
                {
                    b.HasOne("Norm.Database.Entities.NovelInfo", "NovelInfo")
                        .WithMany("AssociatedGuildNovelRegistrations")
                        .HasForeignKey("NovelInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NovelInfo");
                });

            modelBuilder.Entity("Norm.Database.Entities.MovieNightAndSuggestion", b =>
                {
                    b.HasOne("Norm.Database.Entities.GuildMovieNight", "MovieNight")
                        .WithMany("MovieNightAndSuggestions")
                        .HasForeignKey("MovieNightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Norm.Database.Entities.GuildMovieSuggestion", "MovieSuggestion")
                        .WithMany("MovieNightAndSuggestions")
                        .HasForeignKey("MovieSuggestionId", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieNight");

                    b.Navigation("MovieSuggestion");
                });

            modelBuilder.Entity("Norm.Database.Entities.GuildMovieNight", b =>
                {
                    b.Navigation("MovieNightAndSuggestions");
                });

            modelBuilder.Entity("Norm.Database.Entities.GuildMovieSuggestion", b =>
                {
                    b.Navigation("MovieNightAndSuggestions");
                });

            modelBuilder.Entity("Norm.Database.Entities.NovelInfo", b =>
                {
                    b.Navigation("AssociatedGuildNovelRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
